name: "car-garage"

services:
  api:
    container_name: cargarage-api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ../api:/var/www/api
    depends_on:
      - database

  client:
    container_name: cargarage-client
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.client
    ports:
      - '3030:3030'
    volumes:
      - ../client:/var/www/client
      - /var/www/client/node_modules
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: cargarage-database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cargarage
      - MYSQL_USER=cargarage
      - MYSQL_PASSWORD=cargarage
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: cargarage-nginx
    image: nginx:1.25.5
    ports:
      - "80:80"
    volumes:
      - ../nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ../nginx/client.conf:/etc/nginx/conf.d/client.conf
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../api/public:/var/www/api/public
    depends_on:
      - client
      - api

volumes:
  database_data:
  db_data:
